<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<title>Demo To Do List</title>
	<link rel="stylesheet" href="bootstrap/css/bootstrap.css">


	<script src="lib/angular/angular.js"></script>
	<script src="lib/angular/angular-resource.js"></script>
	<script src="js/app.js"></script>
	
</head>


<body class="well" ng-app="todoApp" ng-controller="AppCtrl">



<h1>Things To Do</h1>

<p>
	Remaining <strong>{{remaining()}}</strong> of <strong>{{items.length}}</strong>
	[ <a href ng-click="archive()">archive</a> ]
</p>


	<ul class="unstyled">
		<li ng-repeat="item in items">
			<input type="checkbox" ng-model="item.state" ng-click="update(item)" ><a href="#/tasks/{{item.task_id}}">{{ item.name }}</a>
		</li>
	</ul>


<form>
	<input ng-model="newItem.name">
	<button class="btn btn-primary" 
		ng-click="add(newItem)"
		ng-disabled="!newItem.name">add</button>
</form>

</body>
</html>